source 'https://github.com/CocoaPods/Specs.git'
# 使用frameworks
use_frameworks!
# 忽略pod里面警告
inhibit_all_warnings!
# 支持的平台
platform :ios, '14.0'


##################
#      PODS      #
##################

# === 私有组件 === #
def pods_private
  # 本地路径
  $root = '../../../'
 
  $basic = 'Basic/'
  $ui = 'UI/'
  $business = 'Business/'
  $server = 'Server/'
  
  
  # Basic
  pod 'SFBase',         :path => $root + $basic + 'SFBase/'
  pod 'SFExtension',    :path => $root + $basic + 'SFExtension/'
  
  # UI
  
  
  # Business
  
    
  # Server
  pod 'SFLogger',       :path => $root + $server + 'SFLogger/'
  pod 'SFNetwork',    :path => $root + $server + 'SFNetwork/'
 
 
end

# === 第三方组件 === #
def pods_third
  
  
end


##################
#     TARGET     #
##################

# === SFNetwork_Example === #
target 'SFNetwork_Example' do
  
  pods_private
  pods_third
  
end
