use_frameworks!

platform :ios, '10.0'

target 'SFNetwork_Example' do
  pod 'SFNetwork', :path => '../'

  target 'SFNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
